### PR TITLE
style: Fix input boxes and protected email recipient page

### LINKED ISSUE #763: Input box fixes
Input box labels and states are incorrect, please refer to the slides for specific errors.

Please refer to [slide 16-19: Input boxes](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on errors. Input box states can also be viewed in [Figma](https://www.figma.com/file/Wd6jTqpdaqaItVLoyk1Me2/%F0%9F%8E%A8Postman-Design-System?node-id=3640%3A517).

### LINKED ISSUE #850: UI fixes for protected email recipient page
Following UI issues:
1. Desktop width should be 800px
2. Padding should be 40px (`spacing-6`)
3. Standardise message typography with design system
4. Standardise UI elements styles to design system (e.g. horizontal rule)

### PR DESCRIPTION
**Pull request by chinying**
## Problem

Closes #763 
Closes #850 

## Solution
- Use inline error messages for errors from inputs with button
- Add missing styles for SMS Details page to ensure width is correct
- Cleaned up styles for protected message login and preview to align with design system
- Add "Delivered by" footer for protected message

## Screenshots

**Error message for input with button**

image

**Protected message login**

image

**Protected message**

image

### CODE REVIEW

**Comment by lamkeewei** [comment]
@chinying I'll over this and the header freeze issue.

**Comment by jeantanzj** [comment]
Missed the text input button in ApiKey.tsx

**Review by jeantanzj — APPROVED** [review]
Seems ok. But do you also find that the logo in password protected preview awkward?

Add the error message for ApiKey.tsx and we're good to merge :)

**Comment by lamkeewei** [comment]
> Seems ok. But do you also find that the logo in password protected preview awkward?
> 
> Add the error message for ApiKey.tsx and we're good to merge :)

Yeah. Feels a little like it's just hanging there. If the message is short, it would also take up a disproportionate amount of space relative to the message. I think we can consolidate this and other feedback (e.g. empty space above campaigns table?) and let the designers know. 

But I think as a first cut, would be good to at least get most stuff in-sync with the design master and iterate from there with the designers.

Will add fix ApiKey before merge!

**Pull request merged**
