### PR TITLE
feat: Rich text editor

### LINKED ISSUE #801: Rich text format
**Is your feature request related to a problem? Please describe.**
Our users are not tech-savvy and have a hard time learning html code for formatting their emails. 

**Describe the solution you'd like**
[Google doc](https://docs.google.com/document/d/1SxuwY3zPbVeu_xM0P0lVt2MbCPqRc4hjz8Zfaxn3Qmk/edit?usp=sharing)

### PR DESCRIPTION
**Pull request by lamkeewei**
Hosted at https://richtext.postman.gov.sg. Make sure that workers are also deployed.

## Problem

Closes #801 

## Solution

[Design doc](https://docs.google.com/document/d/1SxuwY3zPbVeu_xM0P0lVt2MbCPqRc4hjz8Zfaxn3Qmk/edit)

As we require quite significant customisation, quite a number of components had to be implemented. These components can be broadly be broken down into the following categories:

- Controls
   - Custom implementations of different controls on the toolbar
   - Includes:
      - `BlockTypeControl`
      - `FontColorControl`
      - `ImageControl`
      - `InlineControl`
      - `LinkControl`
      - `ListControl`
      - `TableControl`
      - `TextAlignControl` 
- Blocks
   - Custom implementations of block types
   - Includes:
      - `ImageBlock`
      - `TableWrapper`  
- Decorators
   - Custom way to decorate existing blocks with additional UI (e.g. tooltip for deletion for links)
   - Includes:
      - `VariableDecorator`
      - `LinkDecorator`

In addition, custom conversions to and from Draft.js to HTML has to be implemented. This can be found in `Converter.ts`. The main functions are:
- `convertFromHTML`
- `convertToHTML`

## Before & After Screenshots
image

## Tests
**Variables**
- Variables should be highlighted within the text editor as per usual

**Text sizes**
- Check that you are able to set different text sizes (Normal, Title, Subtitle and Header)
- Based on the position of the cursor, the active text sizes should be reflected in the toolbar
- Text sizes cannot be set within:
   - Table cells
   - Lists
- Ensure that text sizes are preserved in preview and sent email

**Text colors**
- Check that you are able to set different text colors by selecting from the dropdown menu
- Active color should be reflected in the toolbar based on the position of the cursor
- Check that text colors can be applied within:
   - Lists
   - Different text styles (Title, Subtitle, etc)
   - Within table cells
- Ensure that text colors are preserved in preview and sent email

**Text alignment**
- Check that you are able to set different text alignment by selecting from the dropdown menu
- Ensure that preview shows the correct text alignment
- Active text alignment should be reflected in the toolbar based on the position of the cursor
- Ensure that text alignment is preserved in preview and sent email

**Bold, italic and underline**
- Check that you are able to set different text decoration by selecting from the toolbar
- Active text decoration should be reflected in the toolbar based on the position of the cursor
- Check that text decoration can be applied within:
   - Lists
   - Different text styles (Title, Subtitle, etc)
   - Within table cells
- Ensure that text decoration are preserved in preview and sent email

**Lists**
- Ensure that ordered and unordered lists are supported
- Active list style should be reflected in the toolbar
- Nesting of lists should be supported
- Nesting level can be changed by `Tab` or `Shift + Tab`
- Ensure that lists and nesting levels are preserved in preview and sent email

**Links**
- Links can be inserted by through the toolbar
- Highlighting text and then selecting link icon in the toolbar should automatically populate the title field
- Link URL can be revealed in the tooltip by clicking within the link
- Link can be removed through the tooltip
- Links are preserved in preview and sent email

**Images**
- Images can be inserted by providing an Image URL
- Image preview should be shown
- Image can be deleted through the tooltip
- Image size can be changed through the tooltip
- Ensure that images are preserved in preview and sent email

**Tables**
- Different sizes of tables can be inserted through the toolbar selector
- Text and variables can be entered within the table cell
- Table columns should be equally spaced in preview and sent email with border
- Tables can be deleted by selecting from the line before to the line after the table
- The line before and after the table cannot be deleted to allow for selection for deletion

**Copy and pasting**
- Create a word document and apply some styles to the text
- Copy and paste text into the rich text editor
- Styles should be stripped

## Deploy Notes

- Worker deploy required

**New dependencies**:
- `draft-js` : Framework for building rich text editors
- `draftjs-to-html` : Conversion from Draft.js ContentState to HTML
- `html-to-draftjs` : Conversion from HTML to Draft.js ContentState 
- `react-draft-wysiwyg`: Basic toolbar and formatting elements

## TODOs
- Link support
   - [x] Custom control for inserting link
   - [x] Custom decorator to show link on mouseover/click
   - [x] Support inline unlink
- Image support
   - [x] Custom control for inserting image
   - [x] Custom render image block 
   - [x] Inline options to resize and remove image
   - [x] Restrict to only percentage for dimension
- Table support
   - [x] Custom control for inserting tables
   - [x] Custom table block to render table
   - [x] Custom export for table block to HTML
- Copy pasting / Import
   - [x] Implement strategy for backward compatibility for existing templates
   - [x] Tests for import/export to and from HTML
   - [x] ~Sanitise input on paste~ Replaced with stripPastedStyles. Backend will also sanitise on save.
- Miscellaneous 
   - [x] Fix message preview CSS. Currently overflows width.
   - [x] ~Add editor to protected email Message B~ Will add in once we are sure it works for normal email
   - [x] Disable delete last line after table

### CODE REVIEW

**Comment by miazima** [comment]
Styles that did not appear in the preview
- Lists and nested lists
- text colours
- text alignment
- table borders

Unexpected behaviour
- When adding text decoration or colours to text and clicking next, if we go back to the previous create message step, there are newlines or removed spaces introduced to the message template

Observations (may be expected behaviour)
- Unable to insert table in between text lines
- Text sizes can be set within lists but the list behaviour is lost
- The subtitle text size is a thin font in Postman but displays as a bold text in Gmail (feels inconsistent)

**Comment by lamkeewei** [comment]
> Styles that did not appear in the preview
> 
> * Lists and nested lists
> * text colours
> * text alignment
> * table borders
> 
> Unexpected behaviour
> 
> * When adding text decoration or colours to text and clicking next, if we go back to the previous create message step, there are newlines or removed spaces introduced to the message template
> 
> Observations (may be expected behaviour)
> 
> * Unable to insert table in between text lines
> * Text sizes can be set within lists but the list behaviour is lost
> * The subtitle text size is a thin font in Postman but displays as a bold text in Gmail (feels inconsistent)

Let me fix these. Haven't done super thorough checks for the preview.

**Comment by lamkeewei** [comment]
@miazima fixed the following:

1. All preview issues
2. Unable to insert table in between text lines

Still looking at:
1. Text sizes can be set within lists but the list behaviour is lost
2. When adding text decoration or colours to text and clicking next, if we go back to the previous create message step, there are newlines or removed spaces introduced to the message template

**Comment by lamkeewei** [comment]
@miazima resolved the issues except for:
>The subtitle text size is a thin font in Postman but displays as a bold text in Gmail (feels inconsistent). 

Spoke to the designers before about this. We will keep it like this for now first. Wanted to respect each email client's styling rather than overriding them. 

> Text sizes can be set within lists but the list behaviour is lost

I can't reproduce this. Let me know if it's still an issue.

**Comment by miazima** [comment]
Previous issues with preview styles have been resolved. Tested backward compatibility with a few templates, works great!

**Minor issues**
When starting off the template with a list, we get a weird state with the placeholder and the bullet, and its not possible to delete the list in this state. But all returns to normal once we enter text.
image

Link tooltip overflows the message template textarea when it is towards the end of the box and introduces horizontal scroll.
image

**Comment by lamkeewei** [comment]
> When starting off the template with a list, we get a weird state with the placeholder and the bullet, and its not possible to delete the list in this state. But all returns to normal once we enter text.

For this were you able to toggle the link state with the toolbar? Pressing enter might work too. Am aware of this quirk, but might not be able to fix it easily given how Draft.js works.
 
> Link tooltip overflows the message template textarea when it is towards the end of the box and introduces horizontal scroll.

Will see if I can fix this!

**Comment by miazima** [comment]
> When starting off the template with a list, we get a weird state with the placeholder and the bullet, and its not possible to delete the list in this state. But all returns to normal once we enter text.

Ah yes pressing enter works and selecting the list again undoes the state too! This isn't an issue in that case.

**Comment by lamkeewei** [comment]
> > Link tooltip overflows the message template textarea when it is towards the end of the box and introduces horizontal scroll.
> 
> Will see if I can fix this!

Might not have a good way to fix this. If the entire width of the tooltip is longer than the whole textarea, scrolling is inevitable. Originally I was thinking of changing the alignment to left or right of the link based on the position of the the link. But this will not address the issue where the whole tooltip is longer than the textarea. 

The longer term fix is to render and absolute position the tooltip as a sibling of the top level text editor div so that it will "float" instead of triggering a scroll.

**Comment by miazima** [comment]
> The longer term fix is to render and absolute position the tooltip as a sibling of the top level text editor div so that it will "float" instead of triggering a scroll.

As discussed, let's deal with this in a future issue

**Review by miazima — APPROVED** [review]

**Pull request merged**
