### PR TITLE
feat(frontend): make info banner fixed and colorful

### LINKED ISSUE #1454: Make banner more visible and sticky
**Is your feature request related to a problem? Please describe.**
Current banner is small and user won't see if once they scroll down slightly

**Describe the solution you'd like**
Make banner sticky so they can see at any point of time.

### PR DESCRIPTION
**Pull request by stanleynguyen**
resolves #1454

Changes:
- info banner fixed on top

https://user-images.githubusercontent.com/12974927/161680637-4349141f-ca50-4edd-8220-4d2d015b2f78.mov

- 3 different color mode for info banner `primary`, `warning`, and `danger` for different kinda messages

Screenshot 2022-04-05 at 11 42 09 AM

Screenshot 2022-04-05 at 11 43 02 AM

Screenshot 2022-04-05 at 11 43 38 AM

- simplify info banner to take info from env directly since that's the only it's being used rn

### CODE REVIEW

**Review by prestonlimlianjie — COMMENTED** [review]
PR looks good in general. Could we change the yellow to a darker color for better contrast?

**Comment by stanleynguyen** [comment]
> PR looks good in general. Could we change the yellow to a darker color for better contrast?

Changed to 700
Screenshot 2022-04-13 at 10 08 39 AM

**Comment by lisatjide** [comment]
add instructions on how to activate these when we need for ops and pm

**Review by prestonlimlianjie — APPROVED** [review]
lgtm

**Pull request merged**
