### PR TITLE
fix: update swagger for transactional/email/send

### PR DESCRIPTION
**Pull request by yingyee0111**
## Problem

document api /transactional/email/send 

## Note

Not sure which error codes from cloudflare are relevant to our clients. Things like SSL errors are on us to fix but idk if we should let them know?

### CODE REVIEW

**Comment by gweiying** [comment]
Would love to sync up with you on this before this is reviewed!

**Review by stanleynguyen — APPROVED** [review]

**Comment by stanleynguyen** [comment]
> Would love to sync up with you on this before this is reviewed!

@gweiying let's update this doc again in the attachment PR

**Review by gweiying — APPROVED** [review]
lgtm

**Comment by gweiying** [comment]
> > Would love to sync up with you on this before this is reviewed!
> 
> @gweiying let's update this doc again in the attachment PR

Can also merge into my PR if that makes more sense

**Pull request merged**
