### PR TITLE
feat: make database triggers explicit

### PR DESCRIPTION
**Pull request by tan-zx**
## Problem

Closes https://github.com/opengovsg/postmangovsg/issues/1713

## Solution

- Formally add migration for `format_user_on_insert` and `format_user_trigger`; these already exist on staging and production
- Add `format_email_from_address` and `format_email_from_address_trigger`; these do not currently exist and are nice-to-have
- Formally add `add_user` database function migration + comments on usage; these already exist on staging and production
- Remove all the extra db functions from staging and production that are not in use (see comment below)

## Deployment Checklist

- [x] To run against staging to make sure everything works as intended
- [ ] For staging and production, since they alr have `format_user_trigger`, manually add `20220914082001-add_format_user_on_insert.js` to the`sequelize_meta` table to avoid migration errors. (Not an issue for database functions like `add_user`, since those would be replaced by default.)
- [x] Tested on staging
- [ ] To do on production

### CODE REVIEW

**Comment by tan-zx** [comment]
Diffs of the migrated functions (left is local) vs what was originally in production (should be all just formatting differences):

`add_user`
image

`format_user_on_insert`
image

`log_next_job`
image

`retry_jobs_email`
image

`retry_jobs_sms`
image

`update_stats`
image

**Comment by tan-zx** [comment]
hmm did not work; found out that an extra step to create the trigger is needed.

SSH-ed into the staging db and found the current trigger. only 1 trigger exists. 
```
Triggers:
    format_user_trigger BEFORE INSERT OR UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE
 format_user_on_insert()
```

image

**Comment by tan-zx** [comment]
was tracing the code and it seems like, out of the functions that are missing on local:
- `add_user`: not found in codebase
- `format_user_on_insert`: used in database trigger
- `log_next_job`: not found in codebase (only specific variants like `log_next_job_[email|sms|telegram]` are found in `loaders/message-worker/index.ts`)
- `retry_jobs_email`: not found in codebase (only general `retry_jobs` is used in `job.service.ts`)
- `retry_jobs_sms`: not found in codebase (only general `retry_jobs` is used in `job.service.ts`)
- `update_stats`: not found in codebase (only specific `update_stats_[email|sms|telegram]` are found

should the right course of action be to **_delete_** all the functions (except for `format_user_on_insert`) from staging and production, instead of adding them to local via a database migration? @stanleynguyen

**Comment by tan-zx** [comment]
Talked to Kee Wei:
- `add_users` was a utility method to add someone that was not of whitelisted email domain → we shall retain this in a database migration and annotate clearly that it is meant to be triggered manually (and hence not invoked directly in the codebase)
- previously, intern has made sure that all required database functions are already in database migrations

For the remaining functions, to remove on staging and test first, before doing the same on production.

**Review by prestonlimlianjie — APPROVED** [review]
lgtm

**Pull request merged**
