### PR TITLE
ci(github-actions): run all tests on PR to develop

### LINKED ISSUE #1401: Run unit and integration tests on CI
Also add more CI checks - build, lint the frontend for example

### PR DESCRIPTION
**Pull request by stanleynguyen**
Resolves #1401 
Pending #1475 to run `detect-secrets` during CI 

~~No-longer-valid test cases (removed from frontend-test) (needs help from @lamkeewei  to confirm):~~
~~- protected email › displays an error if the subject contains extraneous invalid params (Reason: params are only evaluated at the upload CSV step, not at the template creation)~~
~~- protected email › displays an error if the subject contains extraneous invalid params (same as above)~~
~~- protected email › displays an error if the body contains extraneous invalid params (same as above)~~

### CODE REVIEW

**Comment by lamkeewei** [comment]
@stanleynguyen for protected email, you can only use `{{protectedlink}}` or `{{recipient}}` in your cover message template.

**Comment by stanleynguyen** [comment]
> @stanleynguyen for protected email, you can only use `{{protectedlink}}` or `{{recipient}}` in your cover message template.

The this feature seems to actually not work as I managed to perform the same activities as the test without being flagged 🤔

**Comment by stanleynguyen** [comment]
Ready for review @prestonlimlianjie @lamkeewei

**Review by prestonlimlianjie — APPROVED** [review]
lgtm

**Pull request merged**
