### PR TITLE
test(cypress): add test case for txnal emails

### PR DESCRIPTION
**Pull request by stanleynguyen**
## Problem

_What problem are you trying to solve? What issue does this close?_

[Ticket](https://www.notion.so/opengov/Add-API-calls-in-Cypress-test-12723e30029e4c8ba79bd22437d073df)

## Solution

Implement it

## Deployment Checklist

_Any tasks that need to be done on the environment before releasing of this PR (e.g. Setting environment variables, running migrations, etc). If there's no task to be done, put "N/A"_

- [ ] N/A

### CODE REVIEW

**Comment by tan-zx** [comment]
haha you should write up your experience debugging this thing :P

**Review by richard-yak — APPROVED** [review]
LGTM tbh

**Comment by tan-zx** [comment]
@stanleynguyen if you don't mind, I'm gonna try to clean this up a bit, e.g.
- move the cypress credentials and stuff from the root folder to the cypress folder
- look into sharing the login states across the frontend tests (so we don't need to login once for every test)

can be part of this PR or another PR; think this would be a good way for me to become more familiar with cypress

**Comment by stanleynguyen** [comment]
> @stanleynguyen if you don't mind, I'm gonna try to clean this up a bit, e.g.
> 
> * move the cypress credentials and stuff from the root folder to the cypress folder
> * look into sharing the login states across the frontend tests (so we don't need to login once for every test)
> 
> can be part of this PR or another PR; think this would be a good way for me to become more familiar with cypress

Actually cypress is quite 💩  (Almost died working on this PR). Let's propose to move to another framework?

**Comment by tan-zx** [comment]
Let's use Playwright hehe

**Pull request merged**
