### PR TITLE
feat: Disable delivery report download for redacted campaigns

### LINKED ISSUE #811: [Redaction] Disable download of delivery report for redacted campaigns
- One week after a campaign had been sent:
	- Disable "Delivery report" download button on both campaign table and campaign statistics page
	- Return an error stating that the campaign had been redacted for `GET /export` 
- Include additional copywriting on statistics page to inform users the date on which their campaign will be redacted. Example of copywriting and placement below.

### PR DESCRIPTION
**Pull request by lamkeewei**
## Problem

Closes #811 

## Solution

**Features**:

- Add check if campaign sent is greater than `redaction.maxAge` for `GET /export` route
- Include `redacted` attribute in API response for `GET /campaigns` and `GET /campaign/:campaignId/:channelType`
- On the frontend, if campaign has been redacted:
   - Remove download delivery report button on main campaign table and on campaign detail page
   - Add notice that campaign has been redacted
- Add notice to inform user that delivery report is only available for 14 days post-campaign sending.
   - For why 14 days refer to #845 

### When will a campaign be redacted?
A campaign will only be redacted if all of the following criteria have been met: 
1. All messages have been sent (unsent count is `0`)
2. 14 or more days have elapsed since the job belonging to the campaign in the job queue has been logged. If the campaign has more than 1 job, the `updated_at` time of the latest job will be used. 

Campaigns in the following scenarios **SHOULD NOT** be redacted:
1. Campaigns that have not been sent
2. Campaigns that started sending more than 14 days ago but was paused midway

Chose not to use the timestamp in the statistics table as that gets updated when callbacks returns. 

## Before & After Screenshots

**Campaign table showing redaction**

**Campaign details page for redacted campaign**

**Campaign details page for not yet redacted campaign**

## Tests

**Expired campaign**
- Create and send a campaign
- Modify the updated_at time of the job in `job_queue` to 14 or more days earlier
- "Report expired" should be shown on the campaign table
- Delivery report button should not be shown in the campaign

**Campaigns with more than 1 job**
_When the send rate is higher than what 1 worker can handle, multiple jobs are created._
- Create and send a campaign
- Manually insert a duplicated job for the campaign
- Modify one of the jobs to have an `updated_at` timestamp to be 14 or more days earlier
- Campaign should not be expired as we consider the later timestamp if there's more than 1 job. In this case, the unmodified job's timestamp is still within the 14 days. 

**Paused campaign**
- Create and pause a campaign
- Modify the updated_at time of the job in `job_queue` to 14 or more days earlier
- Delivery button should not be disabled

### CODE REVIEW

**Comment by NatMaeTan** [comment]
On the dashboard, the text can be changed to "Report expired" and be in the disabled color style Alloy #C1C7CD 

For the post-sending screen, the text can be 
"Delivery report will expire 7 days after sending is completed."

and once expired,
"Delivery report has expired and is no longer available for download."

**Comment by lamkeewei** [comment]
> On the dashboard, the text can be changed to "Report expired" and be in the disabled color style Alloy #C1C7CD
> 
> For the post-sending screen, the text can be
> "Delivery report will expire 7 days after sending is completed."
> 
> and once expired,
> "Delivery report has expired and is no longer available for download."

Should the button still be shown on the post-sending page after the campaign has expired?

**Comment by NatMaeTan** [comment]
The button can be removed since there is nothing for users to do, and it will also help clear the UI.

**Comment by NatMaeTan** [comment]
Ideally, could the UI look like this? We recommend putting the sentence in an information notice for UI consistency

Post-sending_ReportDownload

Post-sending_ReportExpired

See this screen in figma [here](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=5224%3A24575)

**Comment by lamkeewei** [comment]
Note: Merge this only after we collected some data about delivery report download for a week from GA.

**Comment by jeantanzj** [comment]
No job to email user about imminent redaction?

**Comment by lamkeewei** [comment]
> No job to email user about imminent redaction?

Will be a separate PR.

**Review by jeantanzj — APPROVED** [review]

**Pull request merged**
